# Canonical Phase 1 validation/error codes.
CRITICAL = {
    "UNKNOWN_PRODUCT",
    "UNKNOWN_MATERIAL",
    "UNKNOWN_WO",
    "INVALID_DECIMAL",
    "INVALID_DATE",
    "MISSING_REQUIRED_COLUMN",
    "GL_UNBALANCED_DOCUMENT",
    "UNKNOWN_ROUTING",
    "UNKNOWN_WORK_CENTER",
    "INVALID_ROUTING_OPERATION_SEQ",
    "ROUTING_WORK_CENTER_MISSING",
}

ERROR = {
    "BOM_ISSUE",
    "BOM_OVER_ISSUE",
    "BOM_UNDER_ISSUE",
    "HOURS_SUM_MISMATCH",
    "WO_UOM_MISMATCH",
    "PERIOD_KEY_INCONSISTENT",
    "PERIOD_MISMATCH",
    "PERIOD_CLOSED",
    "AMOUNT_MISMATCH",
    "NEGATIVE_QUANTITY",
    "NEGATIVE_OVERTIME",
    "ROUTING_PRODUCT_MISMATCH",
    "ROUTING_OPERATION_MISSING",
    "ROUTING_OPERATION_CODE_MISSING",
    "INVALID_STANDARD_HOURS",
}

WARNING = {
    "NOT_IN_BOM",
    "UNMAPPED_GL",
    "EXCESSIVE_LABOR_HOURS",
    "DUPLICATE_FILE",
}

REVIEW = {
    "MAPPING_AMBIGUOUS",
    "TOLERANCE_AMBIGUOUS",
    "UOM_CONVERSION_MISSING",
    "REWORK_REVIEW_REQUIRED",
}

ALL_CODES = CRITICAL | ERROR | WARNING | REVIEW
