# Canonical Phase 1 validation/error codes.
CRITICAL = {
    "UNKNOWN_PRODUCT",
    "UNKNOWN_MATERIAL",
    "UNKNOWN_WO",
    "INVALID_DECIMAL",
    "INVALID_DATE",
    "MISSING_REQUIRED_COLUMN",
    "GL_UNBALANCED_DOCUMENT",
    "UNKNOWN_ROUTING",
    "UNKNOWN_WORK_CENTER",
    "INVALID_ROUTING_OPERATION_SEQ",
    "ROUTING_WORK_CENTER_MISSING",
    "UNKNOWN_COST_ELEMENT",
}

ERROR = {
    "BOM_ISSUE",
    "BOM_OVER_ISSUE",
    "BOM_UNDER_ISSUE",
    "HOURS_SUM_MISMATCH",
    "WO_UOM_MISMATCH",
    "PERIOD_KEY_INCONSISTENT",
    "PERIOD_MISMATCH",
    "PERIOD_CLOSED",
    "AMOUNT_MISMATCH",
    "NEGATIVE_QUANTITY",
    "NEGATIVE_OVERTIME",
    "ROUTING_PRODUCT_MISMATCH",
    "ROUTING_OPERATION_MISSING",
    "ROUTING_OPERATION_CODE_MISSING",
    "INVALID_STANDARD_HOURS",
    "STANDARD_COST_MISSING",
    "STD_DETAIL_SUM_MISMATCH",
    "GL_RECON_DIFFERENCE",
    "INVALID_LABOR_RATE",
}

WARNING = {
    "NOT_IN_BOM",
    "UNMAPPED_GL",
    "EXCESSIVE_LABOR_HOURS",
    "DUPLICATE_FILE",
}

REVIEW = {
    "MAPPING_AMBIGUOUS",
    "TOLERANCE_AMBIGUOUS",
    "UOM_CONVERSION_MISSING",
    "REWORK_REVIEW_REQUIRED",
    "EXCLUDED_WO",
    "BOM_VERSION_AMBIGUOUS",
}

# 분모(생산량)가 없어 단위원가를 계산할 수 없는 경우. 0%/0원 등 임의값을 반환하지 않는다.
NOT_CALCULABLE = {
    "NO_PRODUCTION_OUTPUT",
    "ZERO_DENOMINATOR",
}

# 배부 근거(overhead_rate)가 없어 OH를 배부하지 않는 경우. 다른 CC 요율을 대신 쓰지 않는다.
NOT_ALLOCATED = {
    "OVERHEAD_NOT_ALLOCATED",
}

ALL_CODES = CRITICAL | ERROR | WARNING | REVIEW | NOT_CALCULABLE | NOT_ALLOCATED
